Project #6 Newsweek clone on the new-feature branch
Janluc/Newsweek-Clone pull request #2
Opened 2020-10-03 16:15 UTC by mke2111

Newsweek clone page designed with HTML, CSS, and Bootstrap to replicate the original page for most if not all of the details.

We used semantic HTML and most of the CSS best practices as possible.

2020-10-03 19:10 UTC, blackpintz requested changes
# Status: Changes Required

## Hello team,

**Great job on your project.**

**Please make the following changes.**

1). **There is some content that is missing above the date on the navbar.**

original | clone
---------| -------
![date_original](https://user-images.githubusercontent.com/38922385/94998163-6b76c800-05b8-11eb-9041-faa2d7ad7281.png) | ![date_clone](https://user-images.githubusercontent.com/38922385/94998170-7598c680-05b8-11eb-8ee5-995911d0f341.png)

2). **The login text on the navbar should be a link.**

3). **The navbar should have a sticky position on all screen sizes.**

4). **There is a lot of empty space on the left and right sides of your body when compared to the original page. Hint: The container class has a big margin-left and margin-right. You can try to reduce the margin values.**

original | clone
-------- | -------
![container_original](https://user-images.githubusercontent.com/38922385/94998309-9e6d8b80-05b9-11eb-9c46-4e46ae23f7ee.png) | ![container_clone](https://user-images.githubusercontent.com/38922385/94998312-a88f8a00-05b9-11eb-8265-4912819eabfd.png)

5). **Please insert the image tags on the left bottom part of the image as shown in the original.**

original | clone
---------| -------
![cultural_original](https://user-images.githubusercontent.com/38922385/94998531-0a042880-05bb-11eb-809e-2625d4c2b4d7.png) | ![cultural_clone](https://user-images.githubusercontent.com/38922385/94998538-138d9080-05bb-11eb-980a-541ed08efaa3.png)

6). **Ensure all the contents in the mid-nav display on one line at 1024px width.** 

original | clone
---------| -------
![midnav_original](https://user-images.githubusercontent.com/38922385/94998825-5b151c00-05bd-11eb-8006-7fdcd9d2072a.png) | ![midnav_clone](https://user-images.githubusercontent.com/38922385/94998827-6405ed80-05bd-11eb-9673-f9fc8267f630.png)

7). **Add space between the main section and the header section, at 768px width. The featured stories and top story titles are hidden by the navbar.**

8).  **Add space between the main section and the header section, at 767px width. The top story title is hidden by the navbar.**

9). **The Newsweek logo in the footer should be a link.**

### Since this is a bootstrap project, you are required to use bootstrap styling instead of custom styling. Only apply custom styling if bootstrap styling is not applicable ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/html_css/using_bootstrap/bootstrap_classes_requirement.png) from pathwright). Please check the comments below for more on this.

### Happy coding 😃.

**PS: You can reach me on slack(Rose Wanjohi).**

2020-10-03 19:10 UTC, ghost commented on styles/styles.css
> +}
This can be implemented using bootstrap `<ul class="list-unstyled">`.

2020-10-03 19:10 UTC, ghost commented on styles/styles.css
> +  text-decoration: none;
`<a href="#" class="text-decoration-none">`.

2020-10-03 19:10 UTC, blackpintz commented on styles/styles.css
> +}
You can use this bootstrap styling `<li class="d-none m-0 p-0">` for line 36-40.

2020-10-03 19:10 UTC, blackpintz commented on styles/styles.css
> +}
The above are a few examples. Most of your CSS styling could easily be done by bootstrap. Please review it.

2020-10-04 03:13 UTC, javitocor requested changes
# STATUS CHANGES REQUIRED ♻️ 

Hello team!
Good job implementing the changes! 👍 
You are so close, just some more small changes and ready to go! 💪 

Please, check my comments below 👇  apply the changes and resubmit your project tfor a new code review. ⏩ 

Good luck with it! 😃 

## Changes

- Navbar should be sticky or fixed for all screen sizes.
- The navbar should take the whole width of the screen
- In the magazine section the first image has a different size than the others, kindly modify it
![Capture1](https://user-images.githubusercontent.com/56809963/95005982-1611d980-05ff-11eb-9e0c-1f149d16fc3c.PNG)
![Capture](https://user-images.githubusercontent.com/56809963/95005983-17db9d00-05ff-11eb-804b-87220842794d.PNG)
- The subscribe section must have 2 images, please add one.
![Capture2](https://user-images.githubusercontent.com/56809963/95005997-48bbd200-05ff-11eb-9cca-bb9b5be992fa.PNG)

![Capture3](https://user-images.githubusercontent.com/56809963/95005996-478aa500-05ff-11eb-804b-1eb8f043211f.PNG)

- For screens under 768px, the order of the sections must be: top story, featured stories, the debate, more stories, my turn, culture&travel. Kindly, make your project like the original.

[OPTIONAL]
Since this is a project to use and learn to use bootstrap, maybe you can try to reduce your CSS, now it is more than 500 lines, try to make it around 400.

2020-10-04 03:13 UTC, javitocor commented on README.md
> +
Add bootstrap in your readme, you will want the recruiters to know that you can use this tech

2020-10-04 15:17 UTC, acushlakoncept requested changes
# Status: Changes Required ♻️

#### Hello @Janluc  and @mke2111, Great job! 👏  

You've done an awesome job so far 👌. But there are still some changes that are necessary for this project to be approved.

In this project, we have to make sure nothing is messed up, please kind fixed the following and you should be good to go.

Please refer to the screenshot below:

- [ ] Let your navbar have a fullwidth on the mobile view

- [ ] Fix the overlapping between the 'subscription offers' and the hamburger menu

- [ ] The width of your page should scale to 100%

- [ ] The Newsweek logo is almost gone, kindly fix it to a proper size

- [ ] The font-color of the footer menu is too faint, kindly fix this too

![mobile](https://user-images.githubusercontent.com/5264771/95019383-f7dac680-065c-11eb-9ee0-b238d05256a9.jpg)

### Cheers and Happy coding! 💻 👏

(Feel free to contact me on slack(@acushla), if you have any additional question)
Uduak Essien
[Twitter](https://twitter.com/acushlakoncept) | [LinkedIn](https://www.linkedin.com/in/acushlakoncept/)

2020-10-05 03:12 UTC, javitocor requested changes
# STATUS CHANGES REQUIRED ♻️ 

Good effort with the requested changes, team! 👍 
Your project looks amazing! ❤️ 
You are so close!
A few more changes and ready to go! ⏩ 
Kindly, check my comments below 👇 

## Changes

- Navbar should be sticky also in big screens, please make it happen
- We are having horizontal scrollbar when the screen is under 1050px, please remove it
- Mobile screens under 768px:
   - The navbar still have some gap on the right side, kindly make it 100% width.
   - The order of the sections must be: top story, featured stories, the debate, opinion, more stories, my turn, culture&travel. Please, make your project to have the same order
- Please fix the signup link
![Capture1](https://user-images.githubusercontent.com/56809963/95036692-0068e680-06c9-11eb-986b-4f8fd8deac13.PNG)
![Capture](https://user-images.githubusercontent.com/56809963/95036694-019a1380-06c9-11eb-9dc9-802a483e89d5.PNG)
- Kindly reduce your lines of CSS, this is a project to use bootstrap framework, so you have to learn to use every class, so more framework and less CSS.

2020-10-05 18:12 UTC, javitocor requested changes
# STATUS CHANGES REQUIRED ♻️ 

Team, good job with the changes made so far! You are so close! 👍 
Two more things and ready to go! 💪 

## Changes

- The navbar should be fixed and 100% width for all screens, please make it happen, on large screens still is not 100% width and not fixed yet.
- For screens below 768px, the order of sections still does not correspond with the original, after opinion comes 'more stories', 'my turn' and 'culture&travel', in that order. Kindly modify it to make it equal to the original

2020-10-05 20:16 UTC, jubaan approved these changes
# Status: Approved :tada: :tada: :tada:

You showed effort and have done great with the project!

## Congrats team you may now merge to master!

## See you at the top :rocket: !

2020-10-05 20:20 UTC, merged